spring:
  application:
    name: currency-provider
  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin@localhost:27017/shedlock?authSource=admin}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
  cloud:
    openfeign:
      client:
        config:
          NBPApiClient:
            url: https://api.nbp.pl/api/exchangerates/tables/c/?format=json
            connectTimeout: 5000
server:
  port: 8082

currency:
  provider:
    schedule-cron: "0 * * * * *"

app:
  query-name: currency.queue
  shedlock-db-name: shedlock
